language: node_js
node_js:
  - '0.10'
addons:
  firefox: '38.0'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'gem install compass'
  - 'bower install'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - './node_modules/protractor/bin/webdriver-manager update'
  - nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
  - 'sleep 3'

script:
  - 'grunt test'
  - 'grunt report'