language: node_js
node_js:
    - '4.1'
addons:
  firefox: '39.0'
before_install:
    - '/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16'
before_script:
    - 'npm install -g bower grunt-cli'
    - 'bower install'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    - './node_modules/protractor/bin/webdriver-manager update'
    - 'sleep 3'

script:
    - 'grunt test'
    - 'grunt report'